// Crypto Investments & Fundraising Data
// High-fidelity institutional dataset matching top Web3 venture firms and recent disclosed raises.

export const FUNDING_METRICS_SUMMARY = {
  roundsTracked: 24,
  displayRoundsTracked: 6,
  fundsCount: 20,
  capitalTracked: "$668M",
  investmentActivity: {
    level: "Low",
    delta: -29,
    description: "Trailing 30-day capital deployment vs previous month",
    gaugeValue: 32, // percentage on speedometer arc (0 to 100)
  },
  topInvestors: {
    activeCount: 7,
    label: "ACTIVE",
    highlightAvatars: [
      { name: "Coinbase Ventures", bg: "#0052FF", text: "C", darkText: false },
      { name: "Binance Labs", bg: "#F3BA2F", text: "B", darkText: true },
      { name: "Pantera Capital", bg: "#10131A", text: "P", darkText: false, border: "1px solid rgba(255,255,255,0.2)" },
      { name: "Andreessen Horowitz", bg: "#FF694B", text: "a16z", darkText: false },
      { name: "Paradigm", bg: "#2E3038", text: "P2", darkText: false },
    ],
  },
  investmentFocus: {
    percentage: "22.9%",
    category: "DEFI",
    slices: [
      { name: "DeFi", value: 22.9, color: "#22d3ee" },
      { name: "Infrastructure", value: 20.4, color: "#3b82f6" },
      { name: "L1/L2", value: 17.5, color: "#8b5cf6" },
      { name: "AI", value: 15.2, color: "#ec4899" },
      { name: "Gaming", value: 12.0, color: "#10b981" },
      { name: "Others", value: 12.0, color: "#f59e0b" },
    ],
  },
};

export const CATEGORIES_LIST = [
  "All",
  "DeFi",
  "Infrastructure",
  "AI",
  "L1/L2",
  "Gaming",
  "Wallet",
  "CEX",
  "Payments",
];

export const VC_FUNDS_DATA = [
  {
    rank: "01",
    id: "coinbase-ventures",
    name: "Coinbase Ventures",
    dealsCount: 83,
    ledCount: 21,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 420,
    bookPercentage: 87,
    latestDeal: {
      project: "Slash",
      amount: "$100M",
      date: "Apr 16",
    },
    focusAreas: ["L1/L2", "DeFi"],
    plusFocus: "+1",
    retailRoi: "+218.4%",
    multiple: "3.18x",
    logoBg: "#0052FF",
    logoText: "C",
    allCategories: ["L1/L2", "DeFi", "Infrastructure", "Payments"],
  },
  {
    rank: "02",
    id: "animoca-brands",
    name: "Animoca Brands",
    dealsCount: 40,
    ledCount: 9,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 485,
    bookPercentage: 100,
    latestDeal: {
      project: "OpenFX",
      amount: "$94M",
      date: "Apr 15",
    },
    focusAreas: ["Gaming", "RWA"],
    plusFocus: "+1",
    retailRoi: "+147.9%",
    multiple: "2.48x",
    logoBg: "#06B6D4",
    logoText: "A",
    allCategories: ["Gaming", "RWA", "Metaverse", "NFT"],
  },
  {
    rank: "03",
    id: "gsr",
    name: "GSR",
    dealsCount: 37,
    ledCount: 6,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 210,
    bookPercentage: 43,
    latestDeal: {
      project: "Midas",
      amount: "$50M",
      date: "Apr 12",
    },
    focusAreas: ["Derivatives", "Infrastructure"],
    plusFocus: null,
    retailRoi: "+92.3%",
    multiple: "1.92x",
    logoBg: "#475569",
    logoText: "G",
    allCategories: ["Derivatives", "Infrastructure", "DeFi", "CEX"],
  },
  {
    rank: "04",
    id: "pantera-capital",
    name: "Pantera Capital",
    dealsCount: 37,
    ledCount: 12,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 310,
    bookPercentage: 64,
    latestDeal: {
      project: "StarkNet Pro",
      amount: "$42M",
      date: "Apr 10",
    },
    focusAreas: ["DeFi", "Infrastructure"],
    plusFocus: "+1",
    retailRoi: "+205.7%",
    multiple: "3.06x",
    logoBg: "#0F172A",
    logoText: "P",
    allCategories: ["DeFi", "Infrastructure", "L1/L2"],
  },
  {
    rank: "05",
    id: "yzi-labs",
    name: "YZi Labs",
    dealsCount: 36,
    ledCount: 11,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 265,
    bookPercentage: 55,
    latestDeal: {
      project: "NovaLedger",
      amount: "$35M",
      date: "Apr 09",
    },
    focusAreas: ["L1/L2", "DeFi"],
    plusFocus: "+1",
    retailRoi: "+178.2%",
    multiple: "2.78x",
    logoBg: "#EAB308",
    logoText: "Y",
    allCategories: ["L1/L2", "DeFi", "AI"],
  },
  {
    rank: "06",
    id: "andreessen-horowitz",
    name: "Andreessen Horowitz",
    dealsCount: 29,
    ledCount: 17,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 140,
    bookPercentage: 29,
    latestDeal: {
      project: "Zenith AI",
      amount: "$60M",
      date: "Apr 08",
    },
    focusAreas: ["AI", "DeFi"],
    plusFocus: "+1",
    retailRoi: "+340.5%",
    multiple: "4.40x",
    logoBg: "#FF694B",
    logoText: "a16z",
    allCategories: ["AI", "DeFi", "Infrastructure", "Gaming"],
  },
  {
    rank: "07",
    id: "mirana-ventures",
    name: "Mirana Ventures",
    dealsCount: 27,
    ledCount: 4,
    tier: "Tier 2",
    isTopTier: false,
    portfolioCount: 180,
    bookPercentage: 37,
    latestDeal: {
      project: "Arcane Protocol",
      amount: "$22M",
      date: "Apr 07",
    },
    focusAreas: ["Infrastructure", "DeFi"],
    plusFocus: null,
    retailRoi: "+112.4%",
    multiple: "2.12x",
    logoBg: "#1E293B",
    logoText: "M",
    allCategories: ["Infrastructure", "DeFi", "Wallet"],
  },
  {
    rank: "08",
    id: "big-brain-holdings",
    name: "Big Brain Holdings",
    dealsCount: 25,
    ledCount: 5,
    tier: "Tier 2",
    isTopTier: false,
    portfolioCount: 165,
    bookPercentage: 34,
    latestDeal: {
      project: "PulseFi",
      amount: "$18M",
      date: "Apr 06",
    },
    focusAreas: ["DeFi", "Gaming"],
    plusFocus: "+1",
    retailRoi: "+98.1%",
    multiple: "1.98x",
    logoBg: "#334155",
    logoText: "BB",
    allCategories: ["DeFi", "Gaming", "Infrastructure"],
  },
  {
    rank: "09",
    id: "galaxy",
    name: "Galaxy",
    dealsCount: 25,
    ledCount: 8,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 150,
    bookPercentage: 31,
    latestDeal: {
      project: "Helion Labs",
      amount: "$55M",
      date: "Apr 04",
    },
    focusAreas: ["Derivatives", "Infrastructure"],
    plusFocus: null,
    retailRoi: "+186.2%",
    multiple: "2.86x",
    logoBg: "#0F172A",
    logoText: "G",
    allCategories: ["Derivatives", "Infrastructure", "CEX"],
  },
  {
    rank: "10",
    id: "amber-group",
    name: "Amber Group",
    dealsCount: 25,
    ledCount: 3,
    tier: "Tier 2",
    isTopTier: false,
    portfolioCount: 140,
    bookPercentage: 29,
    latestDeal: {
      project: "Orbital Quest",
      amount: "$14M",
      date: "Apr 02",
    },
    focusAreas: ["Derivatives", "CEX"],
    plusFocus: null,
    retailRoi: "+74.6%",
    multiple: "1.75x",
    logoBg: "#0284C7",
    logoText: "AM",
    allCategories: ["Derivatives", "CEX", "Payments"],
  },
  {
    rank: "11",
    id: "selini-capital",
    name: "Selini Capital",
    dealsCount: 25,
    ledCount: 2,
    tier: "Tier 2",
    isTopTier: false,
    portfolioCount: 120,
    bookPercentage: 25,
    latestDeal: {
      project: "Quasar",
      amount: "$9M",
      date: "Mar 30",
    },
    focusAreas: ["DeFi", "Derivatives"],
    plusFocus: null,
    retailRoi: "+88.3%",
    multiple: "1.88x",
    logoBg: "#3B82F6",
    logoText: "S",
    allCategories: ["DeFi", "Derivatives"],
  },
  {
    rank: "12",
    id: "paradigm",
    name: "Paradigm",
    dealsCount: 24,
    ledCount: 14,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 95,
    bookPercentage: 20,
    latestDeal: {
      project: "Nexa Bridge",
      amount: "$70M",
      date: "Mar 28",
    },
    focusAreas: ["Infrastructure", "L1/L2"],
    plusFocus: "+1",
    retailRoi: "+412.8%",
    multiple: "5.13x",
    logoBg: "#10B981",
    logoText: "P",
    allCategories: ["Infrastructure", "L1/L2", "DeFi", "AI"],
  },
  {
    rank: "13",
    id: "tether",
    name: "Tether",
    dealsCount: 24,
    ledCount: 9,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 80,
    bookPercentage: 16,
    latestDeal: {
      project: "RWA Bridge",
      amount: "$30M",
      date: "Mar 26",
    },
    focusAreas: ["Payments", "RWA"],
    plusFocus: null,
    retailRoi: "+68.9%",
    multiple: "1.69x",
    logoBg: "#059669",
    logoText: "₮",
    allCategories: ["Payments", "RWA", "Wallet"],
  },
  {
    rank: "14",
    id: "borderless-capital",
    name: "Borderless Capital",
    dealsCount: 20,
    ledCount: 2,
    tier: "Tier 3",
    isTopTier: false,
    portfolioCount: 95,
    bookPercentage: 20,
    latestDeal: {
      project: "Iris Wallet",
      amount: "$5M",
      date: "Mar 22",
    },
    focusAreas: ["Wallet", "Payments"],
    plusFocus: null,
    retailRoi: "+52.1%",
    multiple: "1.52x",
    logoBg: "#6366F1",
    logoText: "B",
    allCategories: ["Wallet", "Payments", "DeFi"],
  },
  {
    rank: "15",
    id: "polychain",
    name: "Polychain",
    dealsCount: 19,
    ledCount: 11,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 125,
    bookPercentage: 26,
    latestDeal: {
      project: "Quanta",
      amount: "$40M",
      date: "Mar 20",
    },
    focusAreas: ["Infrastructure", "Restaking"],
    plusFocus: null,
    retailRoi: "+295.4%",
    multiple: "3.95x",
    logoBg: "#0F172A",
    logoText: "PC",
    allCategories: ["Infrastructure", "Restaking", "L1/L2"],
  },
  {
    rank: "16",
    id: "multicoin-capital",
    name: "Multicoin Capital",
    dealsCount: 18,
    ledCount: 4,
    tier: "Tier 2",
    isTopTier: false,
    portfolioCount: 105,
    bookPercentage: 22,
    latestDeal: {
      project: "MirageFi",
      amount: "$12M",
      date: "Mar 18",
    },
    focusAreas: ["DeFi", "L1/L2"],
    plusFocus: null,
    retailRoi: "+168.3%",
    multiple: "2.68x",
    logoBg: "#4338CA",
    logoText: "MC",
    allCategories: ["DeFi", "L1/L2", "Infrastructure"],
  },
  {
    rank: "17",
    id: "binance-labs",
    name: "Binance Labs",
    dealsCount: 18,
    ledCount: 6,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 220,
    bookPercentage: 45,
    latestDeal: {
      project: "Brave Core",
      amount: "$28M",
      date: "Mar 15",
    },
    focusAreas: ["CEX", "DeFi"],
    plusFocus: "+1",
    retailRoi: "+146.7%",
    multiple: "2.47x",
    logoBg: "#F3BA2F",
    logoText: "BNB",
    allCategories: ["CEX", "DeFi", "Gaming", "AI"],
  },
  {
    rank: "18",
    id: "dragonfly",
    name: "Dragonfly",
    dealsCount: 18,
    ledCount: 7,
    tier: "Tier 1",
    isTopTier: true,
    portfolioCount: 135,
    bookPercentage: 28,
    latestDeal: {
      project: "Zephyr",
      amount: "$18M",
      date: "Mar 12",
    },
    focusAreas: ["DeFi", "L1/L2"],
    plusFocus: null,
    retailRoi: "+222.9%",
    multiple: "3.23x",
    logoBg: "#090A0F",
    logoText: "><",
    allCategories: ["DeFi", "L1/L2", "Payments"],
  },
  {
    rank: "19",
    id: "framework-ventures",
    name: "Framework Ventures",
    dealsCount: 16,
    ledCount: 4,
    tier: "Tier 2",
    isTopTier: false,
    portfolioCount: 110,
    bookPercentage: 23,
    latestDeal: {
      project: "Latch Labs",
      amount: "$8M",
      date: "Mar 09",
    },
    focusAreas: ["Infrastructure", "AI"],
    plusFocus: null,
    retailRoi: "+119.4%",
    multiple: "2.19x",
    logoBg: "#1E293B",
    logoText: "F",
    allCategories: ["Infrastructure", "AI", "DeFi"],
  },
  {
    rank: "20",
    id: "dwf-labs",
    name: "DWF Labs",
    dealsCount: 15,
    ledCount: 3,
    tier: "Tier 2",
    isTopTier: false,
    portfolioCount: 90,
    bookPercentage: 19,
    latestDeal: {
      project: "MirrorX",
      amount: "$10M",
      date: "Mar 06",
    },
    focusAreas: ["Derivatives", "CEX"],
    plusFocus: null,
    retailRoi: "+83.1%",
    multiple: "1.83x",
    logoBg: "#0F172A",
    logoText: "DWF",
    allCategories: ["Derivatives", "CEX", "DeFi"],
  },
];

export const FUNDING_DEALS_DATA = [
  {
    id: "slash",
    name: "Slash",
    round: "Series B",
    amount: "$100M",
    valuation: "$1.2B",
    category: "L1/L2",
    date: "Apr 16, 2026",
    leadInvestor: "Coinbase Ventures",
    leadLogo: "#0052FF",
    leadText: "C",
    coInvestors: [
      { name: "Pantera Capital", bg: "#0F172A", text: "P" },
      { name: "Paradigm", bg: "#10B981", text: "P2" },
      { name: "Dragonfly", bg: "#090A0F", text: "><" },
    ],
    description: "Next-generation programmable zk-rollup with instant finality for institutional settlement.",
    website: "https://slash.network",
    status: "Completed",
  },
  {
    id: "openfx",
    name: "OpenFX",
    round: "Series A",
    amount: "$94M",
    valuation: "$650M",
    category: "Gaming",
    date: "Apr 15, 2026",
    leadInvestor: "Animoca Brands",
    leadLogo: "#06B6D4",
    leadText: "A",
    coInvestors: [
      { name: "Binance Labs", bg: "#F3BA2F", text: "BNB" },
      { name: "Big Brain Holdings", bg: "#334155", text: "BB" },
    ],
    description: "Cross-engine metaverse rendering pipeline and on-chain gaming asset liquidity network.",
    website: "https://openfx.gg",
    status: "Completed",
  },
  {
    id: "midas",
    name: "Midas",
    round: "Strategic",
    amount: "$50M",
    valuation: "$500M",
    category: "DeFi",
    date: "Apr 12, 2026",
    leadInvestor: "GSR",
    leadLogo: "#475569",
    leadText: "G",
    coInvestors: [
      { name: "Galaxy", bg: "#0F172A", text: "G" },
      { name: "Amber Group", bg: "#0284C7", text: "AM" },
    ],
    description: "Algorithmic institutional yield synthesizer for tokenized cash-equivalent assets.",
    website: "https://midas.app",
    status: "Completed",
  },
  {
    id: "starknet-pro",
    name: "StarkNet Pro",
    round: "Series B",
    amount: "$42M",
    valuation: "$850M",
    category: "Infrastructure",
    date: "Apr 10, 2026",
    leadInvestor: "Pantera Capital",
    leadLogo: "#0F172A",
    leadText: "P",
    coInvestors: [
      { name: "Polychain", bg: "#0F172A", text: "PC" },
      { name: "Multicoin Capital", bg: "#4338CA", text: "MC" },
    ],
    description: "Enterprise zero-knowledge proof prover market and recursive verification infrastructure.",
    website: "https://starknetpro.org",
    status: "Completed",
  },
  {
    id: "novaledger",
    name: "NovaLedger",
    round: "Series A",
    amount: "$35M",
    valuation: "$380M",
    category: "L1/L2",
    date: "Apr 09, 2026",
    leadInvestor: "YZi Labs",
    leadLogo: "#EAB308",
    leadText: "Y",
    coInvestors: [
      { name: "Framework Ventures", bg: "#1E293B", text: "F" },
      { name: "Selini Capital", bg: "#3B82F6", text: "S" },
    ],
    description: "High-throughput parallelized execution EVM with sub-millisecond atomic transactions.",
    website: "https://novaledger.io",
    status: "Completed",
  },
  {
    id: "zenith-ai",
    name: "Zenith AI",
    round: "Seed",
    amount: "$60M",
    valuation: "$450M",
    category: "AI",
    date: "Apr 08, 2026",
    leadInvestor: "Andreessen Horowitz",
    leadLogo: "#FF694B",
    leadText: "a16z",
    coInvestors: [
      { name: "Coinbase Ventures", bg: "#0052FF", text: "C" },
      { name: "Paradigm", bg: "#10B981", text: "P2" },
    ],
    description: "Decentralized inference co-processors orchestrating cryptographic LLM execution proofs.",
    website: "https://zenithai.network",
    status: "Completed",
  },
  {
    id: "arcane-protocol",
    name: "Arcane Protocol",
    round: "Series A",
    amount: "$22M",
    valuation: "$210M",
    category: "Infrastructure",
    date: "Apr 07, 2026",
    leadInvestor: "Mirana Ventures",
    leadLogo: "#1E293B",
    leadText: "M",
    coInvestors: [
      { name: "DWF Labs", bg: "#0F172A", text: "DWF" },
      { name: "GSR", bg: "#475569", text: "G" },
    ],
    description: "Zero-knowledge cross-chain messaging protocol with threshold cryptographic state bridges.",
    website: "https://arcane.xyz",
    status: "Completed",
  },
  {
    id: "pulsefi",
    name: "PulseFi",
    round: "Seed",
    amount: "$18M",
    valuation: "$140M",
    category: "DeFi",
    date: "Apr 06, 2026",
    leadInvestor: "Big Brain Holdings",
    leadLogo: "#334155",
    leadText: "BB",
    coInvestors: [
      { name: "Pantera Capital", bg: "#0F172A", text: "P" },
      { name: "Selini Capital", bg: "#3B82F6", text: "S" },
    ],
    description: "Dynamic concentrated liquidity Automated Market Maker with AI volatility protection.",
    website: "https://pulsefi.finance",
    status: "Completed",
  },
  {
    id: "helion-labs",
    name: "Helion Labs",
    round: "Series B",
    amount: "$55M",
    valuation: "$620M",
    category: "Derivatives",
    date: "Apr 04, 2026",
    leadInvestor: "Galaxy",
    leadLogo: "#0F172A",
    leadText: "G",
    coInvestors: [
      { name: "Coinbase Ventures", bg: "#0052FF", text: "C" },
      { name: "Amber Group", bg: "#0284C7", text: "AM" },
    ],
    description: "Hybrid on-chain/off-chain central limit order book for perpetuals and crypto options.",
    website: "https://helion.trade",
    status: "Completed",
  },
  {
    id: "nexa-bridge",
    name: "Nexa Bridge",
    round: "Series A",
    amount: "$70M",
    valuation: "$780M",
    category: "Infrastructure",
    date: "Mar 28, 2026",
    leadInvestor: "Paradigm",
    leadLogo: "#10B981",
    leadText: "P2",
    coInvestors: [
      { name: "Polychain", bg: "#0F172A", text: "PC" },
      { name: "Dragonfly", bg: "#090A0F", text: "><" },
    ],
    description: "Universal interoperability substrate connecting Solana, Ethereum L2s, and Cosmos rollups.",
    website: "https://nexabridge.com",
    status: "Completed",
  },
];
